// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { join } from 'path';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: join(__dirname, 'schema.prisma'),
  migrations: {
    path: join(__dirname, 'migrations'),
  },
  datasource: {
    url: env('PAYMENTS_DB_URL'),
  },
});
