           env:
             - name: FILE_SERVICE_HOST
               valueFrom:
                 secretKeyRef:
                   name: gateway-api-production-config-secret
                   key: FILE_SERVICE_HOST
             - name: FILE_SERVICE_PORT
               valueFrom:
                 secretKeyRef:
                   name: gateway-api-production-config-secret
                   key: FILE_SERVICE_PORT
             - name: IS_SWAGGER_ENABLED
               valueFrom:
                 secretKeyRef:
                   name: gateway-api-production-config-secret
                   key: IS_SWAGGER_ENABLED
             - name: SEND_INTERNAL_SERVER_ERROR_DETAILS
               valueFrom:
                 secretKeyRef:
                   name: gateway-api-production-config-secret
                   key: SEND_INTERNAL_SERVER_ERROR_DETAILS
             - name: INCLUDE_TESTING_MODULE
               valueFrom:
                 secretKeyRef:
                   name: gateway-api-production-config-secret
                   key: INCLUDE_TESTING_MODULE
             - name: COST_FACTOR
               valueFrom:
                 secretKeyRef:
                   name: gateway-api-production-config-secret
                   key: COST_FACTOR
             - name: DATABASE_URL
               valueFrom:
                 secretKeyRef:
                   name: gateway-api-production-config-secret
                   key: DATABASE_URL
             - name: EMAIL
               valueFrom:
                 secretKeyRef:
                   name: gateway-api-production-config-secret
                   key: EMAIL
             - name: EMAIL_PASS
               valueFrom:
                 secretKeyRef:
                   name: gateway-api-production-config-secret
                   key: EMAIL_PASS
             - name: EMAIL_HOST
               valueFrom:
                 secretKeyRef:
                   name: gateway-api-production-config-secret
                   key: EMAIL_HOST
             - name: EMAIL_PORT
               valueFrom:
                 secretKeyRef:
                   name: gateway-api-production-config-secret
                   key: EMAIL_PORT
             - name: CORS_ORIGIN
               valueFrom:
                 secretKeyRef:
                   name: gateway-api-production-config-secret
                   key: CORS_ORIGIN
             - name: ACCESS_TOKEN_SECRET
               valueFrom:
                 secretKeyRef:
                   name: gateway-api-production-config-secret
                   key: ACCESS_TOKEN_SECRET
             - name: REFRESH_TOKEN_SECRET
               valueFrom:
                 secretKeyRef:
                   name: gateway-api-production-config-secret
                   key: REFRESH_TOKEN_SECRET
             - name: ACCESS_TOKEN_EXPIRE_IN
               valueFrom:
                 secretKeyRef:
                   name: gateway-api-production-config-secret
                   key: ACCESS_TOKEN_EXPIRE_IN
             - name: REFRESH_TOKEN_EXPIRE_IN
               valueFrom:
                 secretKeyRef:
                   name: gateway-api-production-config-secret
                   key: REFRESH_TOKEN_EXPIRE_IN
             - name: THROTTLE_TTL
               valueFrom:
                 secretKeyRef:
                   name: gateway-api-production-config-secret
                   key: THROTTLE_TTL
             - name: THROTTLE_LIMIT
               valueFrom:
                 secretKeyRef:
                   name: gateway-api-production-config-secret
                   key: THROTTLE_LIMIT
             - name: RECAPTCHA_SECRET
               valueFrom:
                 secretKeyRef:
                   name: gateway-api-production-config-secret
                   key: RECAPTCHA_SECRET
             - name: NODE_ENV
               valueFrom:
                 secretKeyRef:
                   name: gateway-api-production-config-secret
                   key: NODE_ENV
